/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DisplayMode = { 'emergency' : null } |
  { 'minimal' : null } |
  { 'tactical' : null } |
  { 'standard' : null };
export interface EquipmentToggle {
  'helmet' : boolean,
  'enhancedBioMonitoring' : boolean,
  'hudDisplay' : boolean,
  'advancedMedical' : boolean,
  'respirator' : boolean,
  'longJumpModule' : boolean,
  'flashlight' : boolean,
}
export type Faction = { 'hev' : null } |
  { 'hecu' : null } |
  { 'security' : null } |
  { 'combine' : null };
export type GameMode = { 'hl1' : null } |
  { 'hl2' : null };
export interface Loadout { 'name' : string, 'weaponIds' : Array<string> }
export type MarkLevel = { 'I' : null } |
  { 'V' : null } |
  { 'II' : null } |
  { 'IV' : null } |
  { 'III' : null } |
  { 'prototype' : null };
export interface PlayerDTO {
  'settings' : UserSettings,
  'toggles' : EquipmentToggle,
  'loadouts' : Array<Loadout>,
}
export type TabNavStyle = { 'drawer' : null } |
  { 'dropdown' : null };
export interface UserSettings {
  'glowEffect' : boolean,
  'scanlines' : boolean,
  'setupComplete' : boolean,
  'displayMode' : DisplayMode,
  'brightness' : bigint,
  'operatorName' : string,
  'tabNavStyle' : TabNavStyle,
  'hudSize' : bigint,
  'glitchEffects' : boolean,
  'crtFilter' : boolean,
  'faction' : Faction,
  'gameMode' : GameMode,
  'markLevel' : MarkLevel,
  'colorScheme' : string,
}
export interface _SERVICE {
  'deleteLoadout' : ActorMethod<[string], undefined>,
  'getAllPlayers' : ActorMethod<[], Array<[Principal, PlayerDTO]>>,
  'getLoadouts' : ActorMethod<[], Array<Loadout>>,
  'getSettings' : ActorMethod<[], UserSettings>,
  'getToggles' : ActorMethod<[], EquipmentToggle>,
  'saveLoadout' : ActorMethod<[string, Array<string>], undefined>,
  'saveSettings' : ActorMethod<[UserSettings], undefined>,
  'saveToggle' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];