/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DisplayMode = IDL.Variant({
  'emergency' : IDL.Null,
  'minimal' : IDL.Null,
  'tactical' : IDL.Null,
  'standard' : IDL.Null,
});
export const TabNavStyle = IDL.Variant({
  'drawer' : IDL.Null,
  'dropdown' : IDL.Null,
});
export const Faction = IDL.Variant({
  'hev' : IDL.Null,
  'hecu' : IDL.Null,
  'security' : IDL.Null,
  'combine' : IDL.Null,
});
export const GameMode = IDL.Variant({ 'hl1' : IDL.Null, 'hl2' : IDL.Null });
export const MarkLevel = IDL.Variant({
  'I' : IDL.Null,
  'V' : IDL.Null,
  'II' : IDL.Null,
  'IV' : IDL.Null,
  'III' : IDL.Null,
  'prototype' : IDL.Null,
});
export const UserSettings = IDL.Record({
  'glowEffect' : IDL.Bool,
  'scanlines' : IDL.Bool,
  'setupComplete' : IDL.Bool,
  'displayMode' : DisplayMode,
  'brightness' : IDL.Nat,
  'operatorName' : IDL.Text,
  'tabNavStyle' : TabNavStyle,
  'hudSize' : IDL.Nat,
  'glitchEffects' : IDL.Bool,
  'crtFilter' : IDL.Bool,
  'faction' : Faction,
  'gameMode' : GameMode,
  'markLevel' : MarkLevel,
  'colorScheme' : IDL.Text,
});
export const EquipmentToggle = IDL.Record({
  'helmet' : IDL.Bool,
  'enhancedBioMonitoring' : IDL.Bool,
  'hudDisplay' : IDL.Bool,
  'advancedMedical' : IDL.Bool,
  'respirator' : IDL.Bool,
  'longJumpModule' : IDL.Bool,
  'flashlight' : IDL.Bool,
});
export const Loadout = IDL.Record({
  'name' : IDL.Text,
  'weaponIds' : IDL.Vec(IDL.Text),
});
export const PlayerDTO = IDL.Record({
  'settings' : UserSettings,
  'toggles' : EquipmentToggle,
  'loadouts' : IDL.Vec(Loadout),
});

export const idlService = IDL.Service({
  'deleteLoadout' : IDL.Func([IDL.Text], [], []),
  'getAllPlayers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerDTO))],
      ['query'],
    ),
  'getLoadouts' : IDL.Func([], [IDL.Vec(Loadout)], ['query']),
  'getSettings' : IDL.Func([], [UserSettings], ['query']),
  'getToggles' : IDL.Func([], [EquipmentToggle], ['query']),
  'saveLoadout' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'saveSettings' : IDL.Func([UserSettings], [], []),
  'saveToggle' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DisplayMode = IDL.Variant({
    'emergency' : IDL.Null,
    'minimal' : IDL.Null,
    'tactical' : IDL.Null,
    'standard' : IDL.Null,
  });
  const TabNavStyle = IDL.Variant({
    'drawer' : IDL.Null,
    'dropdown' : IDL.Null,
  });
  const Faction = IDL.Variant({
    'hev' : IDL.Null,
    'hecu' : IDL.Null,
    'security' : IDL.Null,
    'combine' : IDL.Null,
  });
  const GameMode = IDL.Variant({ 'hl1' : IDL.Null, 'hl2' : IDL.Null });
  const MarkLevel = IDL.Variant({
    'I' : IDL.Null,
    'V' : IDL.Null,
    'II' : IDL.Null,
    'IV' : IDL.Null,
    'III' : IDL.Null,
    'prototype' : IDL.Null,
  });
  const UserSettings = IDL.Record({
    'glowEffect' : IDL.Bool,
    'scanlines' : IDL.Bool,
    'setupComplete' : IDL.Bool,
    'displayMode' : DisplayMode,
    'brightness' : IDL.Nat,
    'operatorName' : IDL.Text,
    'tabNavStyle' : TabNavStyle,
    'hudSize' : IDL.Nat,
    'glitchEffects' : IDL.Bool,
    'crtFilter' : IDL.Bool,
    'faction' : Faction,
    'gameMode' : GameMode,
    'markLevel' : MarkLevel,
    'colorScheme' : IDL.Text,
  });
  const EquipmentToggle = IDL.Record({
    'helmet' : IDL.Bool,
    'enhancedBioMonitoring' : IDL.Bool,
    'hudDisplay' : IDL.Bool,
    'advancedMedical' : IDL.Bool,
    'respirator' : IDL.Bool,
    'longJumpModule' : IDL.Bool,
    'flashlight' : IDL.Bool,
  });
  const Loadout = IDL.Record({
    'name' : IDL.Text,
    'weaponIds' : IDL.Vec(IDL.Text),
  });
  const PlayerDTO = IDL.Record({
    'settings' : UserSettings,
    'toggles' : EquipmentToggle,
    'loadouts' : IDL.Vec(Loadout),
  });
  
  return IDL.Service({
    'deleteLoadout' : IDL.Func([IDL.Text], [], []),
    'getAllPlayers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerDTO))],
        ['query'],
      ),
    'getLoadouts' : IDL.Func([], [IDL.Vec(Loadout)], ['query']),
    'getSettings' : IDL.Func([], [UserSettings], ['query']),
    'getToggles' : IDL.Func([], [EquipmentToggle], ['query']),
    'saveLoadout' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'saveSettings' : IDL.Func([UserSettings], [], []),
    'saveToggle' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };