/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Loadout {
    name: string;
    weaponIds: Array<string>;
}
export interface UserSettings {
    glowEffect: boolean;
    scanlines: boolean;
    setupComplete: boolean;
    displayMode: DisplayMode;
    brightness: bigint;
    operatorName: string;
    tabNavStyle: TabNavStyle;
    hudSize: bigint;
    glitchEffects: boolean;
    crtFilter: boolean;
    faction: Faction;
    gameMode: GameMode;
    markLevel: MarkLevel;
    colorScheme: string;
}
export interface EquipmentToggle {
    helmet: boolean;
    enhancedBioMonitoring: boolean;
    hudDisplay: boolean;
    advancedMedical: boolean;
    respirator: boolean;
    longJumpModule: boolean;
    flashlight: boolean;
}
export interface PlayerDTO {
    settings: UserSettings;
    toggles: EquipmentToggle;
    loadouts: Array<Loadout>;
}
export enum DisplayMode {
    emergency = "emergency",
    minimal = "minimal",
    tactical = "tactical",
    standard = "standard"
}
export enum Faction {
    hev = "hev",
    hecu = "hecu",
    security = "security",
    combine = "combine"
}
export enum GameMode {
    hl1 = "hl1",
    hl2 = "hl2"
}
export enum MarkLevel {
    I = "I",
    V = "V",
    II = "II",
    IV = "IV",
    III = "III",
    prototype = "prototype"
}
export enum TabNavStyle {
    drawer = "drawer",
    dropdown = "dropdown"
}
export interface backendInterface {
    deleteLoadout(name: string): Promise<void>;
    getAllPlayers(): Promise<Array<[Principal, PlayerDTO]>>;
    getLoadouts(): Promise<Array<Loadout>>;
    getSettings(): Promise<UserSettings>;
    getToggles(): Promise<EquipmentToggle>;
    saveLoadout(name: string, weaponIds: Array<string>): Promise<void>;
    saveSettings(settings: UserSettings): Promise<void>;
    saveToggle(toggleName: string, state: boolean): Promise<void>;
}
import type { DisplayMode as _DisplayMode, EquipmentToggle as _EquipmentToggle, Faction as _Faction, GameMode as _GameMode, Loadout as _Loadout, MarkLevel as _MarkLevel, PlayerDTO as _PlayerDTO, TabNavStyle as _TabNavStyle, UserSettings as _UserSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deleteLoadout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLoadout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLoadout(arg0);
            return result;
        }
    }
    async getAllPlayers(): Promise<Array<[Principal, PlayerDTO]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoadouts(): Promise<Array<Loadout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoadouts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoadouts();
            return result;
        }
    }
    async getSettings(): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_UserSettings_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_UserSettings_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToggles(): Promise<EquipmentToggle> {
        if (this.processError) {
            try {
                const result = await this.actor.getToggles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToggles();
            return result;
        }
    }
    async saveLoadout(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLoadout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLoadout(arg0, arg1);
            return result;
        }
    }
    async saveSettings(arg0: UserSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(to_candid_UserSettings_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(to_candid_UserSettings_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveToggle(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveToggle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveToggle(arg0, arg1);
            return result;
        }
    }
}
function from_candid_DisplayMode_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisplayMode): DisplayMode {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Faction_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Faction): Faction {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_GameMode_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameMode): GameMode {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MarkLevel_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarkLevel): MarkLevel {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerDTO_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerDTO): PlayerDTO {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_TabNavStyle_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TabNavStyle): TabNavStyle {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserSettings_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSettings): UserSettings {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    settings: _UserSettings;
    toggles: _EquipmentToggle;
    loadouts: Array<_Loadout>;
}): {
    settings: UserSettings;
    toggles: EquipmentToggle;
    loadouts: Array<Loadout>;
} {
    return {
        settings: from_candid_UserSettings_n5(_uploadFile, _downloadFile, value.settings),
        toggles: value.toggles,
        loadouts: value.loadouts
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    glowEffect: boolean;
    scanlines: boolean;
    setupComplete: boolean;
    displayMode: _DisplayMode;
    brightness: bigint;
    operatorName: string;
    tabNavStyle: _TabNavStyle;
    hudSize: bigint;
    glitchEffects: boolean;
    crtFilter: boolean;
    faction: _Faction;
    gameMode: _GameMode;
    markLevel: _MarkLevel;
    colorScheme: string;
}): {
    glowEffect: boolean;
    scanlines: boolean;
    setupComplete: boolean;
    displayMode: DisplayMode;
    brightness: bigint;
    operatorName: string;
    tabNavStyle: TabNavStyle;
    hudSize: bigint;
    glitchEffects: boolean;
    crtFilter: boolean;
    faction: Faction;
    gameMode: GameMode;
    markLevel: MarkLevel;
    colorScheme: string;
} {
    return {
        glowEffect: value.glowEffect,
        scanlines: value.scanlines,
        setupComplete: value.setupComplete,
        displayMode: from_candid_DisplayMode_n7(_uploadFile, _downloadFile, value.displayMode),
        brightness: value.brightness,
        operatorName: value.operatorName,
        tabNavStyle: from_candid_TabNavStyle_n9(_uploadFile, _downloadFile, value.tabNavStyle),
        hudSize: value.hudSize,
        glitchEffects: value.glitchEffects,
        crtFilter: value.crtFilter,
        faction: from_candid_Faction_n11(_uploadFile, _downloadFile, value.faction),
        gameMode: from_candid_GameMode_n13(_uploadFile, _downloadFile, value.gameMode),
        markLevel: from_candid_MarkLevel_n15(_uploadFile, _downloadFile, value.markLevel),
        colorScheme: value.colorScheme
    };
}
function from_candid_tuple_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _PlayerDTO]): [Principal, PlayerDTO] {
    return [
        value[0],
        from_candid_PlayerDTO_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    drawer: null;
} | {
    dropdown: null;
}): TabNavStyle {
    return "drawer" in value ? TabNavStyle.drawer : "dropdown" in value ? TabNavStyle.dropdown : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hev: null;
} | {
    hecu: null;
} | {
    security: null;
} | {
    combine: null;
}): Faction {
    return "hev" in value ? Faction.hev : "hecu" in value ? Faction.hecu : "security" in value ? Faction.security : "combine" in value ? Faction.combine : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hl1: null;
} | {
    hl2: null;
}): GameMode {
    return "hl1" in value ? GameMode.hl1 : "hl2" in value ? GameMode.hl2 : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    I: null;
} | {
    V: null;
} | {
    II: null;
} | {
    IV: null;
} | {
    III: null;
} | {
    prototype: null;
}): MarkLevel {
    return "I" in value ? MarkLevel.I : "V" in value ? MarkLevel.V : "II" in value ? MarkLevel.II : "IV" in value ? MarkLevel.IV : "III" in value ? MarkLevel.III : "prototype" in value ? MarkLevel.prototype : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emergency: null;
} | {
    minimal: null;
} | {
    tactical: null;
} | {
    standard: null;
}): DisplayMode {
    return "emergency" in value ? DisplayMode.emergency : "minimal" in value ? DisplayMode.minimal : "tactical" in value ? DisplayMode.tactical : "standard" in value ? DisplayMode.standard : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _PlayerDTO]>): Array<[Principal, PlayerDTO]> {
    return value.map((x)=>from_candid_tuple_n2(_uploadFile, _downloadFile, x));
}
function to_candid_DisplayMode_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisplayMode): _DisplayMode {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Faction_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Faction): _Faction {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_GameMode_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): _GameMode {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_MarkLevel_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarkLevel): _MarkLevel {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_TabNavStyle_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TabNavStyle): _TabNavStyle {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserSettings_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserSettings): _UserSettings {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    glowEffect: boolean;
    scanlines: boolean;
    setupComplete: boolean;
    displayMode: DisplayMode;
    brightness: bigint;
    operatorName: string;
    tabNavStyle: TabNavStyle;
    hudSize: bigint;
    glitchEffects: boolean;
    crtFilter: boolean;
    faction: Faction;
    gameMode: GameMode;
    markLevel: MarkLevel;
    colorScheme: string;
}): {
    glowEffect: boolean;
    scanlines: boolean;
    setupComplete: boolean;
    displayMode: _DisplayMode;
    brightness: bigint;
    operatorName: string;
    tabNavStyle: _TabNavStyle;
    hudSize: bigint;
    glitchEffects: boolean;
    crtFilter: boolean;
    faction: _Faction;
    gameMode: _GameMode;
    markLevel: _MarkLevel;
    colorScheme: string;
} {
    return {
        glowEffect: value.glowEffect,
        scanlines: value.scanlines,
        setupComplete: value.setupComplete,
        displayMode: to_candid_DisplayMode_n19(_uploadFile, _downloadFile, value.displayMode),
        brightness: value.brightness,
        operatorName: value.operatorName,
        tabNavStyle: to_candid_TabNavStyle_n21(_uploadFile, _downloadFile, value.tabNavStyle),
        hudSize: value.hudSize,
        glitchEffects: value.glitchEffects,
        crtFilter: value.crtFilter,
        faction: to_candid_Faction_n23(_uploadFile, _downloadFile, value.faction),
        gameMode: to_candid_GameMode_n25(_uploadFile, _downloadFile, value.gameMode),
        markLevel: to_candid_MarkLevel_n27(_uploadFile, _downloadFile, value.markLevel),
        colorScheme: value.colorScheme
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisplayMode): {
    emergency: null;
} | {
    minimal: null;
} | {
    tactical: null;
} | {
    standard: null;
} {
    return value == DisplayMode.emergency ? {
        emergency: null
    } : value == DisplayMode.minimal ? {
        minimal: null
    } : value == DisplayMode.tactical ? {
        tactical: null
    } : value == DisplayMode.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TabNavStyle): {
    drawer: null;
} | {
    dropdown: null;
} {
    return value == TabNavStyle.drawer ? {
        drawer: null
    } : value == TabNavStyle.dropdown ? {
        dropdown: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Faction): {
    hev: null;
} | {
    hecu: null;
} | {
    security: null;
} | {
    combine: null;
} {
    return value == Faction.hev ? {
        hev: null
    } : value == Faction.hecu ? {
        hecu: null
    } : value == Faction.security ? {
        security: null
    } : value == Faction.combine ? {
        combine: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): {
    hl1: null;
} | {
    hl2: null;
} {
    return value == GameMode.hl1 ? {
        hl1: null
    } : value == GameMode.hl2 ? {
        hl2: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarkLevel): {
    I: null;
} | {
    V: null;
} | {
    II: null;
} | {
    IV: null;
} | {
    III: null;
} | {
    prototype: null;
} {
    return value == MarkLevel.I ? {
        I: null
    } : value == MarkLevel.V ? {
        V: null
    } : value == MarkLevel.II ? {
        II: null
    } : value == MarkLevel.IV ? {
        IV: null
    } : value == MarkLevel.III ? {
        III: null
    } : value == MarkLevel.prototype ? {
        prototype: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
